version: '3'
services:
  # db:
  #   image: postgres
  #   #hostname: postgres
  #   container_name: books-docker-db
  #   environment:
  #     POSTGRES_PASSWORD: books
  #     POSTGRES_USER: books
  #     POSTGRES_DB: books
  #   ports:
  #     #- 5433:5432
  #     - target: 5432
  #       published: 5433
  #       protocol: tcp
  #       mode: host
  #   networks:
  #     - backdb
  #   expose: 
  #     - 5433
  
  back1:
    build: 
      context: ./backend
      args:
        APPLI_CONFIG: back1
    container_name: backend1
    ports:
      - 8080:8080
    networks: 
      - frontback
    # depends_on:
    #   - db
    # networks:
    #   - backdb

  back2:
    build: 
      context: ./backend
      args:
        APPLI_CONFIG: back2
    container_name: backend2
    ports:
      - 8081:8081
    networks: 
      - frontback
    # depends_on:
    #   - db
    # networks:
    #   - backdb

  front:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    networks: 
      - frontback     
  
networks: 
  backdb:
    driver: bridge
  frontback:
    driver: bridge