version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'myblog'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    networks:
      - backdb
  
  back1:
    build: 
      context: ./backend
      args:
        APPLI_CONFIG: back1
    container_name: backend1
    ports:
      - 8080:8080
    networks: 
      - frontback
      - backdb

  back2:
    build: 
      context: ./backend
      args:
        APPLI_CONFIG: back2
    container_name: backend2
    ports:
      - 8081:8081
    networks: 
      - frontback
      - backdb

  front:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    networks: 
      - frontback     
  
networks: 
  backdb:
    driver: bridge
  frontback:
    driver: bridge